# Dockerfile.dev
FROM python:3.12

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    XDG_CACHE_HOME=/cache

# ffmpeg（Whisper用）
RUN apt-get update &&\
    apt-get install -y --no-install-recommends ffmpeg && \
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 依存だけ先に入れてキャッシュを効かせる
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# ソースは開発中はマウントするので COPY しない
EXPOSE 8000

# ホットリロード
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000","--reload"]
